spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    username:
    password:
    url: 'jdbc:h2:file:C:/Users/jmoty/Documents/Programowanie/todoapp/todoapp/todoappdb'
  jpa:
      hibernate:
        dll-auto: validate